/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignment;


import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author User
 */
public class candidate extends javax.swing.JFrame {
      private Statement stmt;
                
    /**
     * Creates new form candidate
     */
    public candidate() {
        initComponents();
    }
    
    
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setText("Add Candidate");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(427, 70, 190, 32);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(92, 153, 100, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NIC Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 220, 88, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(92, 283, 104, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Batch");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(92, 346, 40, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(244, 455, 75, 31);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(276, 146, 137, 35);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(276, 210, 137, 33);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 280, 137, 36);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(276, 339, 137, 34);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "NIC Number", "Phone Number", "Batch"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 150, 462, 244);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(888, 493, 71, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaassignment/IMG-20200728-WA0023.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 990, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                             // TODO add your handling code here:
          viewTable();
          insertData();
                            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new candidate().setVisible(true);
            }
        });
    }
public void viewTable(){
    
                             if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals(""))
                            {
                                JOptionPane.showMessageDialog(this,"Please Enter the all Data ..!");
                            }
                            else{
                                String data[]= {jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText()};
                                
                              DefaultTableModel tb1Model  = (DefaultTableModel)jTable1.getModel();
                              tb1Model.addRow(data);
                              JOptionPane.showMessageDialog(this,"Add Data Successfully ... !");
                              jTextField1.setText("");
                              jTextField2.setText("");
                              jTextField3.setText("");
                              jTextField4.setText("");
                            }
                             
}




 private void initializeDB() {
        try {
            // Load the JDBC driver
            Class.forName("com.mysql.jdbc.Driver");
            // Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("Driver loaded");

            // Establish a connection
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/login", "root", "");
            // ("jdbc:oracle:thin:@liang.armstrong.edu:1521:orcl",
            // "scott", "tiger");
            System.out.println("Database connected");

            // Create a statement
            stmt = connection.createStatement();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }



public void insertData(){
          /*  INSERT INTO `candidate`(`student_name`, `nic_number`, `phone_number`, `batch`)*/
     initializeDB();
        String student_name = jTextField1.getText();
        String nic_number = (jTextField2.getText());
        int phone_number = parseInt(jTextField3.getText());
        String batch = jTextField4.getText();

        try {

            String queryString = "insert into candidate(student_name,nic_number,phone_number, batch) values('" + student_name + "','" + nic_number + "','" + phone_number + "','" + batch + "')";

//            String queryString = "select lastname, firstname, middleinitial, address, city,state,telephone FROM staff where ID = '" + id + "'";
            stmt.executeUpdate(queryString);
            System.out.println("insert successful");
            jLabel3.setText("insert successfull");
           
        } catch (SQLException e) {
            jLabel3.setText("insert unsuccessfull");
            e.printStackTrace();
           
        }
 
        
         
         
         
         
         
         // conn = DriverManager.getConnection("jdbc:mysql://localhost/vote","root","");
          //Class.forName("com.mysql.jdbc.Driver");
          //conn = DriverManager.getConnection(query);
         // pst= conn.prepareStatement(query);
         // String url = "jdbc:mysql://localhost/vote";
         // String user = "root";
         // String password = "";
          
          //Class.forName("com.mysql.jdbc.Driver");
         // conn = DriverManager.getConnection(url, user, password);
          
       //   pst.setString(1,jTextField1.getText());
       //   pst.setString(2,jTextField2.getText());
       //   pst.setString(3,jTextField3.getText());
        //  pst.setString(4,jTextField4.getText());
           
         //  pst.executeUpdate();
         //  JOptionPane.showMessageDialog(this,"Successfull...");
           
          // DB_operation DB= new DB_operation;();
           
 
          
            
          //  String queryString = "insert into candidate(student_name, nic_number, phone_number, batch) values('" + student_name + "','" + nic_number + "','" + phone_number + "','" + batch +  "')";
             
     

} 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
